[graph]
targets = [
  "aarch64-apple-darwin",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "x86_64-pc-windows-msvc",
]
all-features = true

[advisories]
db-urls = ["https://github.com/RustSec/advisory-db"]
yanked = "deny"
unmaintained = "workspace"
unsound = "workspace"
ignore = []

[bans]
multiple-versions = "warn"
wildcards = "deny"
allow-wildcard-paths = true
highlight = "all"
deny = []

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [
  "https://github.com/rust-lang/crates.io-index",
]
